### ISSUE TITLE
attempt to call global 'SMARTBUFF_OnUpdate' (a nil value)

### ISSUE THREAD

**Issue by gravitas425** [Softrix/SmartBuff-WOTLK-Classic#1]
Using r47_30402, no other addons but buggrabber and bugsack. This error is spammed

5728x [string "*SmartBuff.xml:41_OnUpdate"]:1: attempt to call global 'SMARTBUFF_OnUpdate' (a nil value)
[string "*SmartBuff.xml:41_OnUpdate"]:1: in function <[string "*SmartBuff.xml:41_OnUpdate"]:1>

Locals:
self = SmartBuffFrame {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 Center = Texture {
 }
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined @SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 TopRightCorner = Texture {
 }
 GetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 TopLeftCorner = Texture {
 }
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
}
elapsed = 0.696000
(*temporary) = nil
(*temporary) = SmartBuffFrame {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 Center = Texture {
 }
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined @SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 TopRightCorner = Texture {
 }
 GetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 TopLeftCorner = Texture {
 }
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
}
(*temporary) = 0.696000
(*temporary) = "attempt to call global 'SMARTBUFF_OnUpdate' (a nil value)"

**Comment by Softrix** [comment]
I would suggest doing a re-install of the addon and also clear out any settings connected with it inside the wtf folder - I can't replicate that here but I will leave this open for now.

**Comment by gravitas425** [comment]
It wasn't the settings, so I deleted the folder and reinstalled. It immediately displayed a what's new dialog when I logged in and no errors. Thanks for checking and sorry for the false alarm.

**Comment by Softrix** [comment]
Glad its working for you.
